### ISSUE TITLE
How would this work with Premake modules?

### ISSUE THREAD

**Issue by starkos** [mversluys/premake-ghp#2]
More a question than an issue: can this work with Premake modules too? So if I created a module that adds a new feature to Premake (say, an Eclipse exporter maybe), but doesn't have a project associated with it, could I deliver it with GHP?

Also, what about support for C# (or other language) projects?

Thanks!

**Comment by mversluys** [comment]
Yes. Tom mentioned the same and I added support for Premake modules.
https://github.com/mversluys/premake-ghp/wiki/Premake-modules

It follows the same pattern, see if it's in the cache, if it's not downloaded it and then invoke it from within the cache.

I haven't had time to keep pushing it forward in the last couple of weeks, but will be updating the indexer to make premake module discovery more easily.

Even though the documentation talks about this working for C/C++ projects, that's just because this was the use case I was trying to solve. It should work for any language that premake supports, there may need to be more support for exporting/importing in other languages but the fundamentals are the same.

The next feature I'm looking to add is support to help developers know that there are updates available for packages they're using or if there are versions which have been deprecated.

**Comment by starkos** [comment]
Ah, sorry I missed that page, I will check the wiki again. Do you happen to have a link to that conversation with Tom? If so I'll go check it out before I ask too many more questions. Thanks!

**Comment by mversluys** [comment]
I think it was a private conversation with Tom regarding the value of supporting premake modules. Happy to answer any questions. Hoping to find some time to make more improvements.

**Comment by starkos** [comment]
Sounds good. If you haven't noticed it already, there is a [package management discussion going on the Premake developer forums now](https://groups.google.com/forum/#!msg/premake-development/1bo-xKHnBD4/eHv6_2awAQAJ)…
